/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as BPublicIdRouteImport } from './routes/b.$publicId'
import { Route as BriefingsIdRouteImport } from './routes/briefings_.$id'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const BPublicIdRoute = BPublicIdRouteImport.update({
  id: '/b/$publicId',
  path: '/b/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsIdRoute = BriefingsIdRouteImport.update({
  id: '/briefings_/$id',
  path: '/briefings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos_/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/b/$publicId': typeof BPublicIdRoute
  '/briefings/$id': typeof BriefingsIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/b/$publicId': typeof BPublicIdRoute
  '/briefings/$id': typeof BriefingsIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/b/$publicId': typeof BPublicIdRoute
  '/briefings_/$id': typeof BriefingsIdRoute
  '/projetos_/$id': typeof ProjetosIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefings'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/tarefas'
    | '/b/$publicId'
    | '/briefings/$id'
    | '/projetos/$id'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefings'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/tarefas'
    | '/b/$publicId'
    | '/briefings/$id'
    | '/projetos/$id'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/briefings'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/tarefas'
    | '/b/$publicId'
    | '/briefings_/$id'
    | '/projetos_/$id'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingsRoute: typeof BriefingsRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  TarefasRoute: typeof TarefasRoute
  BPublicIdRoute: typeof BPublicIdRoute
  BriefingsIdRoute: typeof BriefingsIdRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$publicId': {
      id: '/b/$publicId'
      path: '/b/$publicId'
      fullPath: '/b/$publicId'
      preLoaderRoute: typeof BPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings_/$id': {
      id: '/briefings_/$id'
      path: '/briefings/$id'
      fullPath: '/briefings/$id'
      preLoaderRoute: typeof BriefingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos_/$id': {
      id: '/projetos_/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingsRoute: BriefingsRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  TarefasRoute: TarefasRoute,
  BPublicIdRoute: BPublicIdRoute,
  BriefingsIdRoute: BriefingsIdRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
